# Generated by Django 4.2.1 on 2023-07-13 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.IntegerField()),
                ('active_slots', models.JSONField(default=dict)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemWeapon',
            fields=[
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Users.item')),
                ('damage_type', models.CharField(choices=[('Physical', 'Physical'), ('Fire', 'Fire'), ('Water', 'Water'), ('Wind', 'Wind'), ('Light', 'Light'), ('Dark', 'Dark')], max_length=10)),
                ('strength', models.IntegerField()),
                ('intelligence', models.IntegerField()),
                ('dexterity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Users.item')),
                ('damage_type', models.CharField(choices=[('Physical', 'Physical'), ('Fire', 'Fire'), ('Water', 'Water'), ('Wind', 'Wind'), ('Light', 'Light'), ('Dark', 'Dark')], max_length=10)),
                ('strength', models.IntegerField()),
                ('intelligence', models.IntegerField()),
                ('dexterity', models.IntegerField()),
            ],
            bases=('Users.item',),
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='Users.character')),
                ('items', models.ManyToManyField(to='Users.item')),
            ],
        ),
    ]
